### ISSUE TITLE
Preload fonts

### ISSUE THREAD

**Issue by ram-you** [Atinux/vueconfto-nuxt#1]
Hi,
I have a problem with preload fonts 
As result, I would like to have something like that :
`<link rel="preload" href="/_nuxt/fonts/5b23eeb.woff2" as="font" type="font/woff2" crossorigin>`

..from my nuxt.config.js:

....
  css: [
    '~assets/css/tailwind.css',
    '~assets/fonts/Ubuntu/index.css',
  ],
...
...
  render: {
    bundleRenderer: {
      shouldPreload: (file, type) => {
        if (type === 'font') return /.woff2/.test(file)
        return ['script', 'style'].includes(type)
      }
    }
  },
...

type of  shouldPreload's  function  returns only 'script' and 'style' and never 'font'
Can you help please? THANKS

**Comment by atinux** [comment]
Cc @manniL too :)

**Comment by TheAlexLichter** [comment]
We have a test for that [here](https://github.com/nuxt/nuxt.js/blob/8e0b5081f2e2719484ad4a0af4902c7b599a0a39/test/fixtures/with-config/nuxt.config.js#L88). Changing the config to
```js
    bundleRenderer: {
      shouldPreload: (file, type) => {
        if (type === 'font') {
          return /.woff2/.test(file)
        }
        return ['script', 'style'].includes(type)
      }
    },
```

will lead to passing tests (which means the woff2 font will be preloaded). You have to have it in `assets` though.

However, I'd suggest using https://github.com/Developmint/nuxt-webfontloader/ for font loading :relaxed:

**Comment by ram-you** [comment]
I don't know why but the 'type' of shouldPreload's function returns only 'script' and 'style' and never 'font'

**Comment by TheAlexLichter** [comment]
@ram-you Which nuxt version do you use?

**Comment by ram-you** [comment]
Version 2.3.4 and the same with "nuxt-edge": "^2.4.0-25759244.498c4f11"
FYI: it works in dev mode and not in production.

**Comment by MarvinMiles** [comment]
Any update on this?

[nuxt-webfontloader](https://github.com/Developmint/nuxt-webfontloader/) which based on [webfontloader](https://github.com/typekit/webfontloader) have same issue with fonts preload - typekit/webfontloader#403

**Comment by khom-outsourcify** [comment]
> We have a test for that [here](https://github.com/nuxt/nuxt.js/blob/8e0b5081f2e2719484ad4a0af4902c7b599a0a39/test/fixtures/with-config/nuxt.config.js#L88). Changing the config to
> 
> ```js
>     bundleRenderer: {
>       shouldPreload: (file, type) => {
>         if (type === 'font') {
>           return /.woff2/.test(file)
>         }
>         return ['script', 'style'].includes(type)
>       }
>     },
> ```
> 
> will lead to passing tests (which means the woff2 font will be preloaded). You have to have it in `assets` though.
> 
> However, I'd suggest using https://github.com/Developmint/nuxt-webfontloader/ for font loading ☺️

Thanks, This's work for me

**Comment by TheAlexLichter** [comment]
Should work with webfontloader and font display swap :relaxed: 	
https://github.com/Developmint/nuxt-webfontloader#adding-google-fonts-with-font-display-option
